server:
  port: ${SERVER_PORT:8081}

app:
  jwt:
    secret-b64: ${JWT_SIGNING_KEY_B64}
    ttl-seconds: ${JWT_TTL_SECONDS:900}


spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-service
              uri: ${ACCOUNTS_URL}
              predicates:
                - Path=/api/v1/iban/**
              filters:
                - name: AddRequestHeader
                  args:
                    name: X-API-KEY
                    value: ${INTERNAL_API_KEY}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finlab_db?currentSchema=gateway}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:dev}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
