server:
  port: ${SERVER_PORT:8081}

app:
  accountsUrl: ${ACCOUNTS_URL:http://localhost:8082}
  jwt:
    secret-b64: ${JWT_SIGNING_KEY_B64}
    ttl-seconds: ${JWT_TTL_SECONDS:900}


spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: fraud-check
              uri: http://accounts-service:8081
              predicates:
                - Path=/api/v1/fraud
              filters:
                - AddRequestHeader=X-API-KEY, ${INTERNAL_API_KEY}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finlab_db?currentSchema=gateway}
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:dev}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
